### ISSUE TITLE
Ambiguity in code

### ISSUE THREAD

**Issue by sharada10** [TangoChen/KinectV2MouseControl#1]
mouse_event(MouseEventFlag.LeftDown | MouseEventFlag.LeftUp, 0, 0, 0, UIntPtr.Zero);
what is the use of this function,if value of MouseEventFlag.LeftDown | MouseEventFlag.LeftUp is 0x0006 what is its use

**Comment by TangoChen** [comment]
This is for combining LeftDown and LeftUp, to do a mouse pressed and released, AKA a mouse (left button) click.
For details on mouse_event function you can check out this link: https://msdn.microsoft.com/en-us/library/windows/desktop/ms646260(v=vs.85).aspx

(Sorry sharada10! I know it's been so late but still better to have an answer yet for future viewers.)
